### ISSUE TITLE
Hope it faster!

### ISSUE THREAD

**Issue by RvMe** [Leonm99/Stable-Diffusion-Video2Video#5]
very useful script, i have used it to make many video
but i find that the time when the vid2vid run a video(such like a 100s video need 24hours) is more longer than put every single flame to process (100*30*5/3600=4.1hours) 
maybe the script  can make full use of my computer's performance and improve the running speed
thank you! vid2vid is my favorite programs!

![图片](https://user-images.githubusercontent.com/56872189/204740179-3c8adf62-92de-4de5-9218-63e6bdf021cf.png)
![图片](https://user-images.githubusercontent.com/56872189/204740296-7f82542d-6c30-4b5f-aa0f-bc11ab970b75.png)
![图片](https://user-images.githubusercontent.com/56872189/204740358-a43fc5c1-ca79-4304-b992-31451ee4a536.png)

**Comment by Leonm99** [comment]
Hello, and thank you for you kind words. i appreciate it!  Unfortunately i dont really know what the problem here is. the script runs  the framse like if you would put them in one by one so i sadly have no clue where all that extra time comes from. 

i will leave this open for now maybe someone happens to know why it takes so much longer for you.

**Comment by Leonm99** [comment]
check this out: https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py

im discontinuing my version of vid2vid since this person seems to have done it better/improved on it. hope it will work well for you!
